server:
  port: 80
spring:
  datasource:
    hikari:
      leakDetectionThreshold: 60000    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:   jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        use_nationalized_character_data: true #mssql 기본 string type을 nvarchar로
  mvc:
    hiddenmethod:      filter:        enabled: true
    contentnegotiation:
      favor-parameter: true #ContentNegotiationViewResolver가 format 파라미터로 지정한 미디어 타입을 사용하도록 설정
      media-types:
        xls: application/vnd.ms-excel
        file: application/octet-stream
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 2500MB
---
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test;AUTO_SERVER=true
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:p6spy:h2:~/test;AUTO_SERVER=true
    username: sa
    password: 
#  datasource:
#    driverClassName: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:sqlserver://localhost:1433;DatabaseName=youth
#    username: sa
#    password: sellic77
  jpa:
#    database: h2
#    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8088
logging:
  level:
    p6spy: debug
---
spring:
  config:    activate:      on-profile:      - local
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test;AUTO_SERVER=true
#    username: sa
#    password: 
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    jdbcUrl: jdbc:p6spy:sqlserver://localhost:1433;DatabaseName=youth
    url: jdbc:p6spy:sqlserver://localhost:1433;DatabaseName=youth
    username: sa
    password: sellic77
  h2:
    console:      enabled: true
      path: /h2-console
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 8088
logging:
  level:
    p6spy: debug