server:
  port: 8088
spring:
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbcUrl: jdbc:sqlserver://localhost:1434;DatabaseName=youthcafe
    url: jdbc:sqlserver://localhost:1434;DatabaseName=youthcafe
    username: sa
    password: youthcafe1  jpa:
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        use_nationalized_character_data: true #mssql 기본 string type을 nvarchar로
  mvc:
    hiddenmethod:      filter:        enabled: true
    contentnegotiation:
      favor-parameter: true #ContentNegotiationViewResolver가 format 파라미터로 지정한 미디어 타입을 사용하도록 설정
      media-types:
        xls: application/vnd.ms-excel
        file: application/octet-stream
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 2500MB
logging:
  config: classpath:log4j2.xml
  level:
    p6spy: info
---
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    jdbcUrl: jdbc:p6spy:sqlserver://15.165.67.152:1433;DatabaseName=shinsegae_test
    url: jdbc:p6spy:sqlserver://15.165.67.152:1433;DatabaseName=shinsegae_test
    username: sa
    password: sellic77&&
#  datasource:
#    driverClassName: com.p6spy.engine.spy.P6SpyDriver
#    url: jdbc:p6spy:sqlserver://localhost:1433;DatabaseName=youth
#    username: sa
#    password: sellic77
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 8088
logging:
  config: classpath:log4j2_dev.xml
  level:
    p6spy: info
---
spring:
  config:    activate:      on-profile:      - local
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:~/test;AUTO_SERVER=true
#    username: sa
#    password: 
  datasource:
    driverClassName: com.p6spy.engine.spy.P6SpyDriver
    jdbcUrl: jdbc:p6spy:sqlserver://15.165.67.152:1433;DatabaseName=shinsegae_test
    url: jdbc:p6spy:sqlserver://15.165.67.152:1433;DatabaseName=shinsegae_test
    username: sa
    password: sellic77&&
  h2:
    console:      enabled: true
      path: /h2-console
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    open-in-view: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
#        format_sql: true
#        use_sql_comments: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 8088
logging:
  config: classpath:log4j2_local.xml
  level:
    p6spy: info