server:
  port: 8080
spring:
  profiles:    active:    - dev  datasource:    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:   jpa:
    open-in-view: true
    database: h2    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate.format_sql: true
